// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestCriteria } from "./BacktestCriteria";
import type { DataCriteria } from "./DataCriteria";
import type { StatsCriteria } from "./StatsCriteria";

export interface AnalysisCriteria { data_criteria: DataCriteria, stats_criteria: StatsCriteria | null, backtest_criteria: BacktestCriteria | null, }