// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WinRate } from "./WinRate";

export interface BacktestMetrics { arr: number, drawdowns: Array<number>, equity_curve: Array<number>, max_drawdown: number, mean_return: number, sharpe_ratio: number, sortino_ratio: number, total_return: number, win_rate_stats: WinRate, }