// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LongSeries } from "./LongSeries";
import type { Relation } from "./Relation";
import type { TriggerIndicator } from "./TriggerIndicator";

export interface BacktestCriteria { indicator_values: Array<number>, trigger_indicator: TriggerIndicator, relation: Relation, cost_per_leg: number | null, rets_weighting_s0_perc: number, long_series: LongSeries, stop_loss: number, long_thresh: number, long_close_thresh: number, short_thresh: number, short_close_thresh: number, }