// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Coint { is_coint: boolean, test_statistic: number, critical_values: [number, number, number], p_value: number, }