// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Exchange } from "./Exchange";
import type { IntervalPeriod } from "./IntervalPeriod";

export interface DataCriteria { exchange: Exchange, asset_0: string, asset_1: string, interval_period: IntervalPeriod, }