// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IntervalPeriod = { "Min": [number, number] } | { "Hour": [number, number] } | { "Day": [number, number] };