// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestMetrics } from "./BacktestMetrics";
import type { PairPrices } from "./PairPrices";
import type { Statistics } from "./Statistics";

export interface PairAnalysis { prices: PairPrices, stats: Statistics, bt_metrics: BacktestMetrics, }