// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PairPrices { series_0: Array<number>, series_1: Array<number>, labels: Array<bigint>, }