// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Relationship } from "./Relationship";

export interface QuickStats { spread: Array<number>, zscore: Array<number>, hedge_ratio: number, half_life: number, relationship: Relationship, }