// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface QuoteExch { binance: number, binance_us: number, bybit: number, coinbase: number, dydx: number, twelve: number, }