// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Relationship { beta_x_to_y: number, beta_y_to_x: number, annual_vol_y: number, annual_vol_x: number, vol_ratio_x_to_y: number, }