// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coint } from "./Coint";

export interface Statistics { coint: Coint, corr: number, half_life: number, hedge_ratio: number, spread: Array<number>, zscore: Array<number>, coint_roll: Array<number>, corr_roll: Array<number>, }