// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpreadType } from "./SpreadType";

export interface StatsCriteria { spread_type: SpreadType, zscore_window: number, roll_window: number, }