// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coint } from "./Coint";
import type { QuickStats } from "./QuickStats";

export interface StatsOutput { stats_static: QuickStats, stats_dynamic: QuickStats, coint: Coint, corr: number, }