// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface WinRate { win_rate: number, opened: number, closed: number, closed_profit: number, }